// Auto-generated by scripts/generate-component-code-snippets.mjs — do not edit by hand

export const shapeLandingHeroCode = `"use client";

import { motion } from "framer-motion";
import { Circle } from "lucide-react";
import { cn } from "@/lib/utils";

function ElegantShape({
  className,
  delay = 0,
  width = 400,
  height = 100,
  rotate = 0,
  gradient = "from-white/[0.08]",
}: {
  className?: string;
  delay?: number;
  width?: number;
  height?: number;
  rotate?: number;
  gradient?: string;
}) {
  return (
    <motion.div
      initial={{
        opacity: 0,
        y: -150,
        rotate: rotate - 15,
      }}
      animate={{
        opacity: 1,
        y: 0,
        rotate: rotate,
      }}
      transition={{
        duration: 2.4,
        delay,
        ease: [0.23, 0.86, 0.39, 0.96],
        opacity: { duration: 1.2 },
      }}
      className={cn("absolute", className)}
    >
      <motion.div
        animate={{
          y: [0, 15, 0],
        }}
        transition={{
          duration: 12,
          repeat: Number.POSITIVE_INFINITY,
          ease: "easeInOut",
        }}
        style={{
          width,
          height,
        }}
        className="relative"
      >
        <div
          className={cn(
            "absolute inset-0 rounded-full",
            "bg-gradient-to-r to-transparent",
            gradient,
            "backdrop-blur-[2px] border-2 border-white/[0.15]",
            "shadow-[0_8px_32px_0_rgba(255,255,255,0.1)]",
            "after:absolute after:inset-0 after:rounded-full",
            "after:bg-[radial-gradient(circle_at_50%_50%,rgba(255,255,255,0.2),transparent_70%)]"
          )}
        />
      </motion.div>
    </motion.div>
  );
}

export function HeroGeometric({
  badge = "Design Collective",
  title1 = "Elevate Your Digital Vision",
  title2 = "Crafting Exceptional Websites",
  description = "Crafting exceptional digital experiences through innovative design and cutting-edge technology.",
  className,
}: {
  badge?: string;
  title1?: string;
  title2?: string;
  description?: string;
  className?: string;
}) {
  const fadeUpVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: (i: number) => ({
      opacity: 1,
      y: 0,
      transition: {
        duration: 1,
        delay: 0.5 + i * 0.2,
        ease: [0.25, 0.4, 0.25, 1],
      },
    }),
  };

  return (
    <div
      className={cn(
        "relative flex min-h-screen w-full items-center justify-center overflow-hidden bg-[#030303]",
        className
      )}
    >
      <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/[0.05] via-transparent to-rose-500/[0.05] blur-3xl" />

      <div className="absolute inset-0 overflow-hidden">
        <ElegantShape
          delay={0.3}
          width={600}
          height={140}
          rotate={12}
          gradient="from-indigo-500/[0.15]"
          className="left-[-10%] top-[15%] md:left-[-5%] md:top-[20%]"
        />

        <ElegantShape
          delay={0.5}
          width={500}
          height={120}
          rotate={-15}
          gradient="from-rose-500/[0.15]"
          className="right-[-5%] top-[70%] md:right-[0%] md:top-[75%]"
        />

        <ElegantShape
          delay={0.4}
          width={300}
          height={80}
          rotate={-8}
          gradient="from-violet-500/[0.15]"
          className="bottom-[5%] left-[5%] md:bottom-[10%] md:left-[10%]"
        />

        <ElegantShape
          delay={0.6}
          width={200}
          height={60}
          rotate={20}
          gradient="from-amber-500/[0.15]"
          className="right-[15%] top-[10%] md:right-[20%] md:top-[15%]"
        />

        <ElegantShape
          delay={0.7}
          width={150}
          height={40}
          rotate={-25}
          gradient="from-cyan-500/[0.15]"
          className="left-[20%] top-[5%] md:left-[25%] md:top-[10%]"
        />
      </div>

      <div className="relative z-10 container mx-auto px-4 md:px-6">
        <div className="mx-auto max-w-3xl text-center">
          <motion.div
            custom={0}
            variants={fadeUpVariants}
            initial="hidden"
            animate="visible"
            className="mb-8 inline-flex items-center gap-2 rounded-full border border-white/[0.08] bg-white/[0.03] px-3 py-1 md:mb-12"
          >
            <Circle className="h-2 w-2 fill-rose-500/80" />
            <span className="text-sm tracking-wide text-white/60">{badge}</span>
          </motion.div>

          <motion.div
            custom={1}
            variants={fadeUpVariants}
            initial="hidden"
            animate="visible"
          >
            <h1 className="mb-6 text-4xl font-bold tracking-tight sm:text-6xl md:mb-8 md:text-8xl">
              <span className="bg-gradient-to-b from-white to-white/80 bg-clip-text text-transparent">
                {title1}
              </span>
              <br />
              <span
                className={cn(
                  "bg-gradient-to-r from-indigo-300 via-white/90 to-rose-300 bg-clip-text text-transparent"
                )}
              >
                {title2}
              </span>
            </h1>
          </motion.div>

          <motion.div
            custom={2}
            variants={fadeUpVariants}
            initial="hidden"
            animate="visible"
          >
            <p className="mx-auto mb-8 max-w-xl px-4 text-base font-light leading-relaxed tracking-wide text-white/40 sm:text-lg md:text-xl">
              {description}
            </p>
          </motion.div>
        </div>
      </div>

      <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-[#030303] via-transparent to-[#030303]/80" />
    </div>
  );
}
`;

export const gridGlowBackgroundCode = `"use client";

import { useRef, useEffect, useMemo, type ReactNode } from "react";
import { cn } from "@/lib/utils";

const DEFAULT_GLOW_COLORS = ["#4A00E0", "#8E2DE2", "#4A00E0"];

export interface GridGlowBackgroundProps {
  children: ReactNode;
  backgroundColor?: string;
  gridColor?: string;
  gridSize?: number;
  glowColors?: string[];
  glowCount?: number;
  className?: string;
}

export default function GridGlowBackground({
  children,
  backgroundColor = "#0a0a0a",
  gridColor = "rgba(255, 255, 255, 0.05)",
  gridSize = 50,
  glowColors = DEFAULT_GLOW_COLORS,
  glowCount = 10,
  className,
}: GridGlowBackgroundProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const glowPalette = useMemo(() => [...glowColors], [glowColors.join("|")]);

  useEffect(() => {
    const canvas = canvasRef.current;
    const container = containerRef.current;
    if (!canvas || !container) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let glows: Glow[] = [];
    let frameId: number;

    class Glow {
      x: number;
      y: number;
      targetX: number;
      targetY: number;
      radius: number;
      speed: number;
      color: string;
      alpha: number;

      constructor() {
        const w = canvas!.width || 400;
        const h = canvas!.height || 300;
        const gs = gridSize;
        this.x = Math.floor(Math.random() * (w / gs)) * gs;
        this.y = Math.floor(Math.random() * (h / gs)) * gs;
        this.targetX = this.x;
        this.targetY = this.y;
        this.radius = Math.random() * 80 + 40;
        this.speed = Math.random() * 0.015 + 0.01;
        this.color =
          glowPalette[Math.floor(Math.random() * glowPalette.length)] ?? "#4A00E0";
        this.alpha = 0;
        this.setNewTarget();
      }

      setNewTarget() {
        const w = canvas!.width || 400;
        const h = canvas!.height || 300;
        const gs = gridSize;
        this.targetX = Math.floor(Math.random() * (w / gs)) * gs;
        this.targetY = Math.floor(Math.random() * (h / gs)) * gs;
      }

      update() {
        this.x += (this.targetX - this.x) * this.speed;
        this.y += (this.targetY - this.y) * this.speed;

        if (
          Math.abs(this.targetX - this.x) < 1 &&
          Math.abs(this.targetY - this.y) < 1
        ) {
          this.setNewTarget();
        }
        if (this.alpha < 1) this.alpha += 0.01;
      }

      draw() {
        ctx!.globalAlpha = this.alpha;
        const grad = ctx!.createRadialGradient(
          this.x,
          this.y,
          0,
          this.x,
          this.y,
          this.radius
        );
        grad.addColorStop(0, this.color);
        grad.addColorStop(1, "transparent");
        ctx!.fillStyle = grad;
        ctx!.beginPath();
        ctx!.arc(this.x, this.y, this.radius, 0, 2 * Math.PI);
        ctx!.fill();
        ctx!.globalAlpha = 1;
      }
    }

    const resize = () => {
      const rect = container.getBoundingClientRect();
      canvas.width = Math.max(1, Math.floor(rect.width));
      canvas.height = Math.max(1, Math.floor(rect.height));
      glows = Array.from({ length: glowCount }, () => new Glow());
    };

    const drawGrid = () => {
      ctx.strokeStyle = gridColor;
      ctx.lineWidth = 1;
      for (let x = 0; x < canvas.width; x += gridSize) {
        ctx.beginPath();
        ctx.moveTo(x, 0);
        ctx.lineTo(x, canvas.height);
        ctx.stroke();
      }
      for (let y = 0; y < canvas.height; y += gridSize) {
        ctx.beginPath();
        ctx.moveTo(0, y);
        ctx.lineTo(canvas.width, y);
        ctx.stroke();
      }
    };

    const animate = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      drawGrid();
      glows.forEach((g) => {
        g.update();
        g.draw();
      });
      frameId = requestAnimationFrame(animate);
    };

    const ro = new ResizeObserver(() => {
      resize();
    });
    ro.observe(container);
    resize();
    animate();

    return () => {
      ro.disconnect();
      cancelAnimationFrame(frameId);
    };
  }, [gridColor, gridSize, glowCount, glowPalette]);

  return (
    <div
      ref={containerRef}
      className={cn("relative h-full min-h-[240px] w-full", className)}
      style={{ backgroundColor }}
    >
      <canvas
        ref={canvasRef}
        className="absolute inset-0 z-0 h-full w-full opacity-50"
      />
      <div className="relative z-10 flex h-full min-h-[inherit] items-center justify-center px-4 py-8">
        {children}
      </div>
    </div>
  );
}
`;

export const tubeCursorCode = `"use client";

import { useEffect, useRef, useCallback } from "react";
import { cn } from "@/lib/utils";

const DEFAULT_TUBE_COLORS = ["#f967fb", "#53bc28", "#6958d5"];
const DEFAULT_LIGHT_COLORS = ["#83f36e", "#fe8a2e", "#ff008a", "#60aed5"];

export type TubesCursorProps = {
  title?: string;
  subtitle?: string;
  caption?: string;
  initialColors?: string[];
  lightColors?: string[];
  lightIntensity?: number;
  titleSize?: string;
  subtitleSize?: string;
  captionSize?: string;
  enableRandomizeOnClick?: boolean;
  className?: string;
  /** Use fixed fullscreen canvas (default) or contained layout for previews */
  embedded?: boolean;
};

function randomColors(count: number) {
  return new Array(count).fill(0).map(
    () =>
      "#" +
      Math.floor(Math.random() * 16777215)
        .toString(16)
        .padStart(6, "0")
  );
}

export function TubesCursor({
  title = "Tubes",
  subtitle = "Cursor",
  caption = "WebGPU / WebGL",
  initialColors = DEFAULT_TUBE_COLORS,
  lightColors = DEFAULT_LIGHT_COLORS,
  lightIntensity = 200,
  titleSize = "text-[80px]",
  subtitleSize = "text-[60px]",
  captionSize = "text-base",
  enableRandomizeOnClick = true,
  className = "",
  embedded = false,
}: TubesCursorProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const wrapperRef = useRef<HTMLDivElement | null>(null);
  const appRef = useRef<{
    tubes?: {
      setColors: (c: string[]) => void;
      setLightsColors: (c: string[]) => void;
    };
    dispose?: () => void;
  } | null>(null);

  const colorsKey = initialColors.join(",");
  const lightsKey = lightColors.join(",");

  const handleRandomize = useCallback(() => {
    const app = appRef.current;
    if (!app?.tubes) return;
    const colors = randomColors(initialColors.length);
    const lights = randomColors(lightColors.length);
    app.tubes.setColors(colors);
    app.tubes.setLightsColors(lights);
  }, [initialColors.length, lightColors.length]);

  useEffect(() => {
    let removeClick: (() => void) | null = null;
    let destroyed = false;

    void (async () => {
      const mod = await import(
        "threejs-components/build/cursors/tubes1.min.js"
      );
      const TubesCursorCtor = (mod as { default?: unknown }).default ?? mod;

      if (!canvasRef.current || destroyed) return;

      const ctor = TubesCursorCtor as (
        el: HTMLCanvasElement,
        opts: {
          tubes: {
            colors: string[];
            lights: { intensity: number; colors: string[] };
          };
        }
      ) => {
        tubes: {
          setColors: (c: string[]) => void;
          setLightsColors: (c: string[]) => void;
        };
        dispose?: () => void;
      };

      const app = ctor(canvasRef.current, {
        tubes: {
          colors: [...initialColors],
          lights: {
            intensity: lightIntensity,
            colors: [...lightColors],
          },
        },
      });

      appRef.current = app;

      if (enableRandomizeOnClick) {
        const attach = () => {
          const target = embedded ? wrapperRef.current : document.body;
          if (!target) return;
          const handler = () => handleRandomize();
          target.addEventListener("click", handler);
          removeClick = () => target.removeEventListener("click", handler);
        };
        queueMicrotask(attach);
      }
    })();

    return () => {
      destroyed = true;
      if (removeClick) removeClick();
      try {
        appRef.current?.dispose?.();
        appRef.current = null;
      } catch {
        // ignore
      }
    };
  }, [
    colorsKey,
    lightsKey,
    lightIntensity,
    enableRandomizeOnClick,
    embedded,
    handleRandomize,
  ]);

  return (
    <div
      ref={wrapperRef}
      className={cn(
        "relative w-full overflow-hidden",
        embedded ? "h-[min(22rem,70vh)]" : "h-screen min-h-[320px]",
        className
      )}
    >
      <canvas
        ref={canvasRef}
        className={cn(
          "block h-full w-full",
          embedded ? "absolute inset-0" : "fixed inset-0"
        )}
      />

      {title || subtitle || caption ? (
        <div className="pointer-events-none relative z-10 flex h-full w-full flex-col items-center justify-center gap-1 select-none md:gap-2">
          <h1
            className={cn(
              "m-0 p-0 font-bold uppercase leading-none text-white drop-shadow-[0_0_20px_rgba(0,0,0,1)]",
              embedded ? "text-3xl md:text-5xl" : titleSize
            )}
          >
            {title}
          </h1>
          <h2
            className={cn(
              "m-0 p-0 font-medium uppercase leading-none text-white drop-shadow-[0_0_20px_rgba(0,0,0,1)]",
              embedded ? "text-2xl md:text-4xl" : subtitleSize
            )}
          >
            {subtitle}
          </h2>
          <p
            className={cn(
              "m-0 p-0 leading-none text-white drop-shadow-[0_0_20px_rgba(0,0,0,1)]",
              embedded ? "text-xs md:text-sm" : captionSize
            )}
          >
            {caption}
          </p>
        </div>
      ) : null}
    </div>
  );
}
`;

export const explosiveTextBurstCode = `"use client";

export interface ExplosiveTextBurstProps {
  /** Default fills the viewport; use a shorter class for embedded previews. */
  rootClassName?: string;
}

export function ExplosiveTextBurst({
  rootClassName = "flex items-center justify-center min-h-screen bg-[#1a1a1a]",
}: ExplosiveTextBurstProps) {
  return (
    <div className={rootClassName}>
      <style>{\`
        .lum-explosive-heading:hover::before,
        .lum-explosive-heading:hover::after {
          content: '';
          position: absolute;
          top: 50%;
          left: 50%;
          width: 200%;
          height: 200%;
          border-radius: 50%;
          transform: translate(-50%, -50%) scale(0);
          animation: lum-explosive-burst 0.8s ease-out forwards;
        }

        .lum-explosive-heading:hover::before {
          background: radial-gradient(circle, rgba(255, 0, 150, 0.6), transparent);
          z-index: -1;
        }

        .lum-explosive-heading:hover::after {
          background: radial-gradient(circle, rgba(0, 200, 255, 0.6), transparent);
          z-index: -2;
        }

        @keyframes lum-explosive-burst {
          0% {
            transform: translate(-50%, -50%) scale(0);
            opacity: 1;
          }
          70% {
            opacity: 0.8;
          }
          100% {
            transform: translate(-50%, -50%) scale(1.5);
            opacity: 0;
          }
        }
      \`}</style>
      <div className="relative inline-block">
        <h1 className="lum-explosive-heading relative inline-block text-5xl tracking-widest text-white transition-transform duration-300 ease-out hover:scale-110">
          Hover Over Me
        </h1>
      </div>
    </div>
  );
}
`;

export const shadowDanceLumousCode = `"use client";

import { motion } from "framer-motion";

export interface ShadowDanceLumousProps {
  rootClassName?: string;
}

export function ShadowDanceLumous({
  rootClassName = "flex min-h-screen items-center justify-center overflow-hidden bg-[#0b0b10] px-6",
}: ShadowDanceLumousProps) {
  return (
    <div className={rootClassName}>
      <div className="relative flex flex-col items-center justify-center">
        <div className="absolute inset-0 -z-10 h-40 w-40 rounded-full bg-cyan-500/20 blur-3xl" />
        <div className="absolute inset-0 -z-10 h-40 w-40 translate-x-14 translate-y-10 rounded-full bg-fuchsia-500/20 blur-3xl" />

        <motion.h1
          initial={{ opacity: 0, y: 18, scale: 0.96 }}
          animate={{
            opacity: 1,
            y: 0,
            scale: 1,
            textShadow: [
              "5px 5px 0 #ff005e, 10px 10px 0 #00d4ff",
              "-5px -5px 0 #00d4ff, -10px -10px 0 #ff005e",
              "5px 5px 0 #ff005e, 10px 10px 0 #00d4ff",
            ],
            rotate: [0, 0.5, -0.5, 0],
          }}
          transition={{
            duration: 2.2,
            ease: "easeInOut",
            repeat: Infinity,
            repeatType: "mirror",
          }}
          className="select-none text-center text-5xl font-black tracking-[0.35em] text-white sm:text-7xl md:text-8xl"
          style={{
            textShadow: "5px 5px 0 #ff005e, 10px 10px 0 #00d4ff",
          }}
        >
          LUMOUS
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.25, duration: 0.6 }}
          className="mt-5 text-center text-sm font-medium tracking-[0.45em] text-white/65 sm:text-base"
        >
          UI LIBRARY FOR DELIGHTFUL INTERFACES
        </motion.p>
      </div>
    </div>
  );
}
`;

export const meltingTextLumousCode = `"use client";

import { motion } from "framer-motion";

export interface MeltingTextLumousProps {
  rootClassName?: string;
}

export function MeltingTextLumous({
  rootClassName = "flex min-h-screen items-center justify-center overflow-hidden bg-[#09090f] px-6",
}: MeltingTextLumousProps) {
  return (
    <div className={rootClassName}>
      <div className="relative flex flex-col items-center">
        <div className="absolute -top-20 h-56 w-56 rounded-full bg-fuchsia-500/20 blur-3xl" />
        <div className="absolute -bottom-20 h-56 w-56 rounded-full bg-cyan-400/20 blur-3xl" />

        <div className="relative overflow-hidden">
          <motion.h1
            initial={{ opacity: 0, y: -10, scale: 0.98 }}
            animate={{
              opacity: 1,
              y: [0, 18, 0],
              scaleY: [1, 1.04, 1],
            }}
            transition={{
              duration: 3,
              ease: "easeInOut",
              repeat: Infinity,
            }}
            className="relative select-none text-center text-6xl font-black uppercase tracking-[0.35em] sm:text-7xl md:text-8xl"
          >
            <span className="bg-gradient-to-r from-[#ff6f61] via-[#ffbd44] to-[#ff6f61] bg-clip-text text-transparent">
              LUMOUS
            </span>

            <motion.span
              aria-hidden="true"
              animate={{
                y: [0, 8, 16, 24],
                opacity: [0.45, 0.4, 0.3, 0],
                scaleY: [1, 1.15, 1.35, 1.6],
              }}
              transition={{
                duration: 3,
                ease: "easeInOut",
                repeat: Infinity,
              }}
              className="pointer-events-none absolute left-0 top-0 -z-10 bg-gradient-to-r from-[#ff6f61] via-[#ffbd44] to-[#ff6f61] bg-clip-text text-transparent blur-[1px]"
            >
              LUMOUS
            </motion.span>

            <motion.span
              aria-hidden="true"
              animate={{
                y: [0, 10, 20, 30],
                opacity: [0.28, 0.25, 0.15, 0],
                scaleY: [1, 1.2, 1.45, 1.7],
              }}
              transition={{
                duration: 3,
                ease: "easeInOut",
                repeat: Infinity,
                delay: 0.15,
              }}
              className="pointer-events-none absolute left-0 top-0 -z-20 bg-gradient-to-r from-[#ff6f61] via-[#ffbd44] to-[#ff6f61] bg-clip-text text-transparent blur-xl"
            >
              LUMOUS
            </motion.span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.25, duration: 0.6 }}
            className="mt-5 text-center text-sm font-medium tracking-[0.45em] text-white/60 sm:text-base"
          >
            MELTING UI EFFECT
          </motion.p>
        </div>
      </div>
    </div>
  );
}
`;

export const matrixLumousCode = `"use client";

import { motion } from "framer-motion";

export interface MatrixLumousProps {
  rootClassName?: string;
}

export function MatrixLumous({
  rootClassName = "relative flex min-h-screen items-center justify-center overflow-hidden bg-[#05080a] px-6",
}: MatrixLumousProps) {
  const rainDrops = Array.from({ length: 28 }, (_, i) => i);

  return (
    <div className={rootClassName}>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(0,255,140,0.12),transparent_55%)]" />
      <div className="absolute inset-0 bg-[linear-gradient(to_bottom,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[length:100%_22px] opacity-20" />

      <div className="lum-matrix-container relative flex flex-col items-center justify-center">
        <motion.h1
          data-text="LUMOUS"
          initial={{ opacity: 0, scale: 0.96, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="lum-matrix-text relative select-none text-center text-6xl font-black tracking-[0.4em] text-[#7CFF9B] sm:text-7xl md:text-8xl"
        >
          LUMOUS
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, duration: 0.6 }}
          className="mt-5 text-center text-sm font-medium tracking-[0.45em] text-[#7CFF9B]/70 sm:text-base"
        >
          LIVE. GLITCH. REACT.
        </motion.p>

        <div className="lum-matrix-rain pointer-events-none absolute inset-0 overflow-hidden">
          {rainDrops.map((drop) => (
            <span
              key={drop}
              className="absolute top-0 block h-[120%] w-px bg-[#7CFF9B]/35 blur-[0.2px]"
              style={{
                left: \`\${(drop * 100) / rainDrops.length}%\`,
                animationDelay: \`\${(drop % 10) * 0.18}s\`,
                animationDuration: \`\${2.8 + (drop % 5) * 0.45}s\`,
                opacity: 0.15 + (drop % 5) * 0.08,
              }}
            />
          ))}
        </div>
      </div>

      <style>{\`
        .lum-matrix-text {
          animation: lum-matrix-glitch 2.2s infinite linear;
          text-shadow:
            0 0 10px rgba(124, 255, 155, 0.35),
            0 0 24px rgba(124, 255, 155, 0.2);
        }

        .lum-matrix-text::before,
        .lum-matrix-text::after {
          content: attr(data-text);
          position: absolute;
          inset: 0;
          left: 0;
          width: 100%;
          height: 100%;
        }

        .lum-matrix-text::before {
          color: rgba(0, 255, 145, 0.75);
          z-index: -1;
          transform: translate(-3px, -1px);
          animation: lum-matrix-glitch 2.2s infinite linear reverse;
        }

        .lum-matrix-text::after {
          color: rgba(0, 200, 255, 0.55);
          z-index: -2;
          transform: translate(3px, 1px);
          animation: lum-matrix-glitch 2.2s infinite linear;
        }

        .lum-matrix-rain span {
          animation-name: lum-matrix-rain;
          animation-timing-function: linear;
          animation-iteration-count: infinite;
        }

        @keyframes lum-matrix-rain {
          0% {
            transform: translateY(-110%);
          }
          100% {
            transform: translateY(110vh);
          }
        }

        @keyframes lum-matrix-glitch {
          0%,
          100% {
            clip-path: polygon(0 0, 100% 0, 100% 45%, 0 45%);
            transform: translate(0);
          }
          33% {
            clip-path: polygon(0 0, 100% 0, 100% 15%, 0 15%);
            transform: translate(-4px, -3px);
          }
          66% {
            clip-path: polygon(0 85%, 100% 85%, 100% 100%, 0 100%);
            transform: translate(4px, 3px);
          }
        }
      \`}</style>
    </div>
  );
}
`;

export const spin3DLumousCode = `"use client";

import { motion } from "framer-motion";

export interface Spin3DLumousProps {
  rootClassName?: string;
}

export function Spin3DLumous({
  rootClassName =
    "flex min-h-screen items-center justify-center overflow-hidden bg-[linear-gradient(135deg,#050508,#0b0b12_55%,#000)] px-6 [perspective:1000px]",
}: Spin3DLumousProps) {
  return (
    <div className={rootClassName}>
      <div className="relative flex items-center justify-center">
        <div className="absolute h-64 w-64 rounded-full bg-cyan-500/15 blur-3xl" />
        <div className="absolute h-64 w-64 translate-x-16 -translate-y-10 rounded-full bg-fuchsia-500/15 blur-3xl" />

        <motion.h1
          initial={{ opacity: 0, scale: 0.92, rotateX: 8 }}
          animate={{
            opacity: 1,
            scale: 1,
            rotateY: 360,
            rotateX: [8, -8, 8],
          }}
          transition={{
            opacity: { duration: 0.5 },
            scale: { duration: 0.5 },
            rotateY: { duration: 4, repeat: Infinity, ease: "linear" },
            rotateX: { duration: 3, repeat: Infinity, ease: "easeInOut" },
          }}
          className="select-none text-center text-5xl font-black uppercase tracking-[0.28em] text-white sm:text-6xl md:text-7xl"
          style={{
            transformStyle: "preserve-3d",
            textShadow:
              "1px 1px 0px #22d3ee, 2px 2px 0px #a855f7, 3px 3px 0px #f472b6, 4px 4px 0px #f59e0b, 5px 5px 0px #60a5fa",
          }}
        >
          LUMOUS
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, duration: 0.6 }}
          className="absolute -bottom-16 text-center text-sm font-medium tracking-[0.45em] text-white/60"
        >
          3D SPIN EFFECT
        </motion.p>
      </div>
    </div>
  );
}
`;

export const splitTextRevealLumousCode = `"use client";

import { motion } from "framer-motion";

export interface SplitTextRevealLumousProps {
  rootClassName?: string;
}

export function SplitTextRevealLumous({
  rootClassName = "flex min-h-screen items-center justify-center overflow-hidden bg-[#07070c] px-6",
}: SplitTextRevealLumousProps) {
  return (
    <div className={rootClassName}>
      <div className="relative flex flex-col items-center justify-center">
        <div className="absolute -top-24 h-64 w-64 rounded-full bg-cyan-500/15 blur-3xl" />
        <div className="absolute -bottom-24 h-64 w-64 rounded-full bg-fuchsia-500/15 blur-3xl" />

        <div className="relative flex items-center overflow-hidden">
          <motion.span
            initial={{ x: "-220%", opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            transition={{ duration: 1.2, ease: "easeOut" }}
            className="select-none text-5xl font-black uppercase tracking-[0.35em] text-white sm:text-6xl md:text-7xl"
          >
            CON
          </motion.span>

          <motion.span
            initial={{ x: "220%", opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            transition={{ duration: 1.2, ease: "easeOut" }}
            className="select-none text-5xl font-black uppercase tracking-[0.35em] text-white sm:text-6xl md:text-7xl"
          >
            JOINED
          </motion.span>

          <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_center,rgba(0,212,255,0.08),transparent_55%)]" />
        </div>

        <motion.p
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.25, duration: 0.6 }}
          className="mt-5 text-center text-sm font-medium tracking-[0.45em] text-white/60 sm:text-base"
        >
          LUMOUS UI • SPLIT REVEAL
        </motion.p>
      </div>
    </div>
  );
}
`;

export const glow3DLumousCode = `"use client";

import { motion } from "framer-motion";

const layers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

const glowShadows = [
  "0 0 30px #ff4d6d",
  "0 0 30px #ff9f1c",
  "0 0 30px #2dd4bf",
  "0 0 30px #38bdf8",
  "0 0 30px #ff4d6d",
];

export interface Glow3DLumousProps {
  rootClassName?: string;
}

export function Glow3DLumous({
  rootClassName = "flex min-h-screen items-center justify-center overflow-hidden bg-[#07070b] px-6 [perspective:1200px]",
}: Glow3DLumousProps) {
  return (
    <div className={rootClassName}>
      <div className="relative">
        <div className="absolute inset-0 -z-10 mx-auto h-72 w-72 rounded-full bg-cyan-500/15 blur-3xl" />
        <div className="absolute inset-0 -z-10 mx-auto h-72 w-72 translate-x-16 translate-y-10 rounded-full bg-fuchsia-500/15 blur-3xl" />

        <motion.figure
          animate={{
            rotateX: [40, 46, 40, 34, 40],
            rotateY: [40, 34, 40, 46, 40],
            rotateZ: [0, 1.5, 0, -1.5, 0],
          }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "easeInOut",
          }}
          className="relative flex items-center justify-center [transform-style:preserve-3d]"
        >
          {layers.map((layer) => (
            <motion.h1
              key={layer}
              initial={{ opacity: 0 }}
              animate={{
                opacity: layer === 0 ? 1 : 0.9 - layer * 0.05,
                textShadow: glowShadows,
              }}
              transition={{
                duration: 10,
                repeat: Infinity,
                ease: "easeInOut",
              }}
              className="absolute w-full select-none px-4 text-center text-5xl font-black uppercase tracking-[0.25em] text-[#06060a] sm:text-6xl md:text-8xl"
              style={{
                transform: \`translateZ(\${layer * 5}px)\`,
                WebkitTextStroke:
                  layer === 0 ? "1px rgba(255,255,255,0.9)" : "0px transparent",
              }}
            >
              LUMOUS UI
            </motion.h1>
          ))}
        </motion.figure>

        <motion.p
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, duration: 0.6 }}
          className="mt-40 text-center text-sm font-medium tracking-[0.5em] text-white/60"
        >
          3D GLOW EFFECT
        </motion.p>
      </div>
    </div>
  );
}
`;
